CREATE DATABASE QL_BANMAYVITINH
GO
USE QL_BANMAYVITINH

CREATE TABLE TBLMAYTINH
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MAMAY	NVARCHAR(10) NULL UNIQUE,
	TENMAY	NVARCHAR(100) NULL,
	DONGIA	INT	NULL,
	GHICHU	NVARCHAR(200) NULL,
	TINHTRANG INT CHECK (TINHTRANG IN (0,1)) --0 HẾT HÀNG, 1 CÒN HÀNG
)

CREATE TABLE TBLCAUHINH
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	MAMAY NVARCHAR(10) NULL FOREIGN KEY(MAMAY) REFERENCES TBLMAYTINH(MAMAY),
	HANG	NVARCHAR(100)	NULL,
	CPU	NVARCHAR(100) NULL,
	GPU NVARCHAR(100) NULL,
	RAM	NVARCHAR(100) NULL,
	HARDDISK	NVARCHAR(100) NULL,	
)

CREATE TABLE TBLLINHKIEN
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MALK	NVARCHAR(10) UNIQUE NULL,
	TENLK NVARCHAR(100),
	DONGIA	INT NULL,
	GHICHU	NVARCHAR(200) NULL,
	TINHTRANG INT CHECK(TINHTRANG IN (0,1)) NULL
)

CREATE TABLE TBLHOADON
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SOHD INT UNIQUE NULL,
	TENKHACH NVARCHAR(100) NULL,
	DIACHI	NVARCHAR(100),
	SDT		INT NULL,
	NGAYMUA	DATE NULL,
	BAOHANH INT NULL,
	THANHTIEN	INT NULL
)

CREATE TABLE TBL_CTHD
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	SOHD INT NULL FOREIGN KEY(SOHD) REFERENCES TBLHOADON(SOHD),
	MAHNANG NVARCHAR(10) NULL,
	SOLUONG INT NULL
)

select MAMAY, MALK, lk.DONGIA,  mt.DONGIA, (SOLUONG*lk.DONGIA) as tienmay, (MALK*lk.DONGIA) as tienlk
from TBL_CTHD ct, TBLLINHKIEN lk, TBLMAYTINH mt, TBLHOADON hd
where ct.MAHNANG = lk.MALK or ct.MAHNANG = mt.MAMAY and ct.SOHD = hd.SOHD


select * from TBLMAYTINH
select * from TBL_CTHD
select * from TBLCAUHINH
select * from TBLHOADON
select * from TBLLINHKIEN
